stages:
  - update
  - build
  - deploy

update:
  stage: update
  image: archlinux:latest
  before_script:
    - echo "Updating system and installing dependencies..."
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm go git hugo dos2unix git-lfs
  script:
    - |
      echo "Using repository directory: $CI_PROJECT_DIR"
      echo "Fetching latest changes from remote..."
      git fetch origin
      echo "Checking out branch $CI_COMMIT_REF_NAME..."
      git checkout $CI_COMMIT_REF_NAME
      git reset --hard origin/$CI_COMMIT_REF_NAME

      # Git LFS Setup
      echo "Setting up Git LFS..."
      git lfs install --local
      export GIT_LFS_SKIP_SMUDGE=1
      git lfs pull || echo "Warning: LFS pull failed, retrying..."
      git lfs fetch --all || echo "Warning: LFS fetch failed, continuing..."

      # Prüfe, ob LFS-Objekte fehlen
      echo "Verfügbare LFS-Dateien:"
      git lfs ls-files

      # Go-Module Update
      echo "Upgrading Go version..."
      latest_go_version=$(go version | awk '{print $3}' | sed 's/go//')
      go mod edit -go "$latest_go_version"
      echo "Running Go module updates..."
      go mod tidy

      # Build-Skript vorbereiten
      echo "Executing update scripts..."
      dos2unix ./build.sh
      chmod +x ./build.sh
      ./build.sh

      # Git-Konfiguration für Commit
      echo "Configuring Git user..."
      git config user.name "CI Pipeline"
      git config user.email "cipipeline@example.com"

      # Änderungen committen (falls vorhanden)
      echo "Staging changes..."
      git add .
      git add content/*
      echo "Committing changes..."
      git commit -m "Automatic update of Go, Hugo and Go dependencies [skip ci]" || echo "No changes to commit"

      # Git Remote setzen und Push ausführen
      echo "Setting Git remote with PAT..."
      git remote set-url origin "https://oauth2:${PAT}@gitlab.erik-skopp.de/ilmenauerschachverein/turniere/schnellschachturnier.git"
      echo "Pulling latest changes..."
      git pull origin $CI_COMMIT_REF_NAME --rebase || echo "No pull needed"
      echo "Pushing changes..."
      git push origin HEAD:$CI_COMMIT_REF_NAME || echo "Push failed, but continuing"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


build:
  stage: build
  image: archlinux:latest
  before_script:
    - pacman -Syu --noconfirm git go hugo python dos2unix
  script:
    - echo "Starting build process using build.sh..."
    - dos2unix ./build.sh
    - sh ./build.sh
    - echo "Running Hugo commands..."
    - hugo mod get
    - hugo mod tidy
    - hugo --gc --minify --enableGitInfo
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  image: archlinux:latest
  before_script:
    - |
      echo "Installing SSH and rsync..."
      pacman -Syu --noconfirm openssh sshpass rsync
  script:
    - |
      echo "Deleting previous files on server..."
      sshpass -p "$isvpass" ssh -o StrictHostKeyChecking=no "webuser@$isvip" "rm -rf /var/www/isst/*"

      echo "Creating directory if not exists..."
      sshpass -p "$isvpass" ssh -o StrictHostKeyChecking=no "webuser@$isvip" "mkdir -p /var/www/isst"

      echo "Transferring new files..."
      sshpass -p "$isvpass" rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" public/ "webuser@$isvip:/var/www/isst/"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
