title = "31. Ilmenauer Schnellschachturnier 2025"
baseURL = "https://isst.ilmenauer-schachverein.de"
defaultContentLanguage = "de" 

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"
  [[module.imports]]
    path = "github.com/gethinode/mod-flexsearch"

[markup] 
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false

[languages]
  [languages.de]
    languageName = "German"
    weight = 1
    title = "31. Ilmenauer Schnellschachturnier 2025"
    contentDir = "content/de"

[menu]
  [[menu.main]]
    name = "Datenschutzerklärung"
    pageRef = "/datenschutz"
    weight = 3
  [[menu.main]]
    name = "Impressum"
    pageRef = "/impressum"
    weight = 3
  [[menu.main]]
    name = "Ilmenauer Schachverein ↗"
    url = "https://ilmenauer-schachverein.de"
    weight = 4
  [[menu.main]]
    name = "Search"
    weight = 5
    [menu.main.params]
      type = "search"
  [[menu.main]]
    name = "GitHub"
    weight = 6
    url = "https://github.com/IlmenauerSchachverein/Schnellschachturnier"
    [menu.main.params]
      icon = "github"
  [[menu.main]]
    name = "Instagram"
    weight = 7
    url = "https://instagram.com/ilmenauer_schachverein"
    [menu.main.params]
      icon = "instagram"
  [[menu.main]]
    name = "Chess-Results"
    url = "https://chess-results.com/tnr1056111.aspx?lan=0"
    weight = 2

[params]
  disableToc = true

  [params.navbar]
    displayTitle = true
    displayLogo = true

  [params.theme]
    default = "light"

  [params.footer]
    displayCopyright = true
    displayPoweredBy = true

  [params.editURL]
    enable = false
    base = ""

  [params.page]
    width = "full"

  [params.logo]
    path = "images/logo.svg"
    dark = "images/logo-dark.svg"
    link = "/"
    width = 40
    height = 20
