name: Build & Deploy Schnellschachturnier

on:
  push:
    branches: [main]

env:
  SSHSERVER: ${{ secrets.SSHSERVER }}
  SSHPW: ${{ secrets.SSHPW }}

jobs:
  update:
    name: Update Go/Hugo Modules & Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
    
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix

      - name: Update Go Modules
        run: |
          hugo mod get github.com/imfing/hextra
          hugo mod get github.com/gethinode/mod-flexsearch
          go mod tidy

      - name: Run build.sh
        run: |
          dos2unix ./build.sh
          chmod +x ./build.sh
          ./build.sh
          
  build:
    name: Build Hugo Site
    needs: update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.148.2"
          extended: true

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Build Site
        run: |
          dos2unix ./build.sh
          chmod +x ./build.sh
          ./build.sh
          hugo --gc --minify --enableGitInfo

      - name: Upload Public Folder
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public/

  deploy:
    name: Deploy via SFTP as webuser
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: public
          path: public

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Upload with SFTP mirror
        env:
          SSHPW: ${{ secrets.SSHPW }}
          SSHSERVER: ${{ secrets.SSHSERVER }}
        run: |
          lftp -u webuser,"$SSHPW" sftp://$SSHSERVER -e "\
            set sftp:auto-confirm yes; \
            set net:max-retries 2; \
            set net:timeout 30; \
            mirror --reverse --delete --verbose --only-newer --parallel=4 public /isst.ilmenauer-schachverein.de; \
            bye"

  mirror-to-gitlab:
    name: Mirror to GitLab
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.name "CI Pipeline"
          git config --global user.email "info@ilmenauer-schachverein.de"
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_PAT }}@gitlab.erik-skopp.de/ilmenauerschachverein/turniere/schnellschachturnier.git"
          git push --force gitlab main
