name: Deploy German

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date
        run: echo "DATETIME=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
     
      - uses: actions/setup-node@v4
        with:
          node-version: 20  
      
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo site
        run: |
          hugo mod get
          hugo mod tidy
          hugo
          
      - name: Prettier
        run: |
            npm install --save-dev --save-exact prettier
            npx prettier --write public/**/*.html

      - name: Deploy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          source: "public/*"
          target: "/var/www/isst"
          rm: true
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Create folder structure
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd /var/www/isst; mv public/* .;  rm -rf public