name: Build & Deploy Schnellschachturnier

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write  

concurrency:
  group: schnellschachturnier-deploy
  cancel-in-progress: true

jobs:
  update:
    name: Update Go/Hugo Modules & Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
    
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix

      - name: Update Go Modules
        run: |
          hugo mod get github.com/imfing/hextra
          hugo mod get github.com/gethinode/mod-flexsearch
          go mod tidy

      - name: Run build.sh
        run: |
          dos2unix ./build.sh
          chmod +x ./build.sh
          ./build.sh
          
  build-deploy:
    name: Build Hugo & Deploy to GitHub Pages
    needs: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.148.2"
          extended: true

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Build Site
        run: |
          dos2unix ./build.sh
          chmod +x ./build.sh
          ./build.sh
          hugo --gc --minify --enableGitInfo

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          cname: isst.ilmenauer-schachverein.de
